version: '2'
# define all services
services:
  app:
    build:
      context: ./
      dockerfile: app.docker
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    links:
      - mysql
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=1123581321"
      - "DB_DATABASE=laravel"
      - "MAIL_DRIVER=null"
      - "LOG_CHANNEL=daily"
  mysql:
    image: mysql:5.7
    volumes:
       - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1123581321
      - MYSQL_DATABASE=laravel
    ports:
      - "33061:3306"
volumes:
    db_data: